/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    skills: Skill;
    'work-experiences': WorkExperience;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'work-experiences': WorkExperiencesSelect<false> | WorkExperiencesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'works-page': WorksPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'works-page': WorksPageSelect<false> | WorksPageSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  projectId: string;
  title: string;
  description: string;
  placement: 'archive' | 'current';
  order?: number | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  imageUrl?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        url?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  link?: string | null;
  repo?: string | null;
  status?: ('in-progress' | 'planning' | 'on-hold') | null;
  progress?: number | null;
  lastUpdated?: string | null;
  expectedCompletion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  category: string;
  level: number;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-experiences".
 */
export interface WorkExperience {
  id: number;
  experienceId: string;
  company: string;
  role: string;
  duration: {
    start: string;
    end: string;
  };
  isCurrent?: boolean | null;
  description: string;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  technologies?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  companyLogo?: (number | null) | Media;
  companyLogoUrl?: string | null;
  companyUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'work-experiences';
        value: number | WorkExperience;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  projectId?: T;
  title?: T;
  description?: T;
  placement?: T;
  order?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featuredImage?: T;
  imageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        url?: T;
        alt?: T;
        id?: T;
      };
  link?: T;
  repo?: T;
  status?: T;
  progress?: T;
  lastUpdated?: T;
  expectedCompletion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  level?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-experiences_select".
 */
export interface WorkExperiencesSelect<T extends boolean = true> {
  experienceId?: T;
  company?: T;
  role?: T;
  duration?:
    | T
    | {
        start?: T;
        end?: T;
      };
  isCurrent?: T;
  description?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        item?: T;
        id?: T;
      };
  companyLogo?: T;
  companyLogoUrl?: T;
  companyUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  languageLabels: {
    english: string;
    indonesian: string;
  };
  languageToggleTitles: {
    toEnglish: string;
    toIndonesian: string;
  };
  navItems: {
    sectionId: 'hero' | 'about' | 'projects' | 'skills' | 'contact';
    label: string;
    id?: string | null;
  }[];
  homeLabel: string;
  backToPortfolioLabel: string;
  socials?:
    | {
        platform: string;
        url: string;
        icon: 'github' | 'instagram' | 'linkedin' | 'twitter' | 'mail' | 'external';
        id?: string | null;
      }[]
    | null;
  uiLabels: {
    projectDetails: string;
    clickToExpand: string;
    repository: string;
    demo: string;
    repoShort: string;
    imageNotFound: string;
    close: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  metadata: {
    title: string;
    description: string;
  };
  hero: {
    bootSequence: string;
    firstLineName: string;
    secondLineName: string;
    roleLabel: string;
    primaryRole: string;
    secondaryRole: string;
    conjunction: string;
    description: string;
    projectsButton: string;
    contactButton: string;
  };
  about: {
    label: string;
    details: string;
    headingBeforeFirstHighlight: string;
    headingFirstHighlight: string;
    headingBetweenHighlights: string;
    headingSecondHighlight: string;
    headingAfterSecondHighlight: string;
    profileMetrics?:
      | {
          label: string;
          value: string;
          accent?: boolean | null;
          id?: string | null;
        }[]
      | null;
    contentBlocks?:
      | {
          title: string;
          body: string;
          highlightTerms?:
            | {
                term: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  projectsSection: {
    subtitle: string;
    title: string;
    archiveLabel: string;
    periodLabel: string;
    viewAllWorksLabel: string;
  };
  skillsSection: {
    subtitle: string;
    title: string;
    systemLabel: string;
    totalLabel: string;
    activeLabel: string;
  };
  contact: {
    subtitle: string;
    heading: string;
    sendEmailLabel: string;
    sendMailCursorLabel: string;
    connectLabel: string;
    email: string;
    footer: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-page".
 */
export interface WorksPage {
  id: number;
  metadata: {
    title: string;
    description: string;
  };
  hero: {
    title: string;
    subtitle: string;
    homeBreadcrumb: string;
    worksBreadcrumb: string;
    experienceStatLabel: string;
    archiveStatLabel: string;
    currentStatLabel: string;
  };
  experienceSection: {
    title: string;
    presentLabel: string;
    responsibilitiesLabel: string;
    noDataLabel: string;
    recordsIndexedLabel: string;
    startLabel: string;
    statusLabel: string;
  };
  allProjectsSection: {
    title: string;
    subtitle: string;
    noDataLabel: string;
  };
  currentWorkSection: {
    title: string;
    subtitle: string;
    progressLabel: string;
    lastUpdatedLabel: string;
    expectedCompletionLabel: string;
    noDataLabel: string;
    activeRecordsLabel: string;
    statusLabels: {
      inProgress: string;
      planning: string;
      onHold: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  languageLabels?:
    | T
    | {
        english?: T;
        indonesian?: T;
      };
  languageToggleTitles?:
    | T
    | {
        toEnglish?: T;
        toIndonesian?: T;
      };
  navItems?:
    | T
    | {
        sectionId?: T;
        label?: T;
        id?: T;
      };
  homeLabel?: T;
  backToPortfolioLabel?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  uiLabels?:
    | T
    | {
        projectDetails?: T;
        clickToExpand?: T;
        repository?: T;
        demo?: T;
        repoShort?: T;
        imageNotFound?: T;
        close?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        bootSequence?: T;
        firstLineName?: T;
        secondLineName?: T;
        roleLabel?: T;
        primaryRole?: T;
        secondaryRole?: T;
        conjunction?: T;
        description?: T;
        projectsButton?: T;
        contactButton?: T;
      };
  about?:
    | T
    | {
        label?: T;
        details?: T;
        headingBeforeFirstHighlight?: T;
        headingFirstHighlight?: T;
        headingBetweenHighlights?: T;
        headingSecondHighlight?: T;
        headingAfterSecondHighlight?: T;
        profileMetrics?:
          | T
          | {
              label?: T;
              value?: T;
              accent?: T;
              id?: T;
            };
        contentBlocks?:
          | T
          | {
              title?: T;
              body?: T;
              highlightTerms?:
                | T
                | {
                    term?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  projectsSection?:
    | T
    | {
        subtitle?: T;
        title?: T;
        archiveLabel?: T;
        periodLabel?: T;
        viewAllWorksLabel?: T;
      };
  skillsSection?:
    | T
    | {
        subtitle?: T;
        title?: T;
        systemLabel?: T;
        totalLabel?: T;
        activeLabel?: T;
      };
  contact?:
    | T
    | {
        subtitle?: T;
        heading?: T;
        sendEmailLabel?: T;
        sendMailCursorLabel?: T;
        connectLabel?: T;
        email?: T;
        footer?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-page_select".
 */
export interface WorksPageSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        homeBreadcrumb?: T;
        worksBreadcrumb?: T;
        experienceStatLabel?: T;
        archiveStatLabel?: T;
        currentStatLabel?: T;
      };
  experienceSection?:
    | T
    | {
        title?: T;
        presentLabel?: T;
        responsibilitiesLabel?: T;
        noDataLabel?: T;
        recordsIndexedLabel?: T;
        startLabel?: T;
        statusLabel?: T;
      };
  allProjectsSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        noDataLabel?: T;
      };
  currentWorkSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        progressLabel?: T;
        lastUpdatedLabel?: T;
        expectedCompletionLabel?: T;
        noDataLabel?: T;
        activeRecordsLabel?: T;
        statusLabels?:
          | T
          | {
              inProgress?: T;
              planning?: T;
              onHold?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}